name: NCSC Pipeline
on: [push]
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn
      - run: yarn run test

  Deploy:
    needs: Build-And-Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ncsc-2022 #Must be unique in Heroku
          heroku_email: wassim.kallel@hotmail.com
